"""Refresh METRICS.md from PyPI + GitHub APIs.

Pulled signals:
- PyPI download counts (last day / week / month) via pypistats.org JSON API.
- GitHub repo metadata (stars, forks, watchers, open issues/PRs).
- GitHub traffic (clones, views, referrers, paths) — last 14 days.

Plugin install proxy: `/plugin marketplace add <owner>/<repo>` is a git
clone under the hood, so daily clone counts approximate plugin installs.

Stdlib only — no extra deps to keep CI fast and the supply chain small.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO = os.environ.get("GITHUB_REPOSITORY", "raintree-technology/docpull")
PKG = os.environ.get("PYPI_PACKAGE", "docpull")
OUTPUT = Path(os.environ.get("METRICS_OUTPUT", "METRICS.md"))


def gh(path: str) -> dict | list:
    """GET against the GitHub REST API via the gh CLI.

    Locally this uses the user's gh auth. In CI, set GH_TOKEN (or
    GITHUB_TOKEN) on the step's env and gh picks it up automatically.
    ``path`` is relative to the configured repo, e.g. ``/traffic/clones``.
    """
    full = f"repos/{REPO}{path}"
    out = subprocess.check_output(
        ["gh", "api", "-H", "X-GitHub-Api-Version: 2022-11-28", full],
        text=True,
    )
    return json.loads(out)


def gh_search_count(q: str) -> int:
    """Use the search API to get a count (total_count is cheap; per_page=1)."""
    out = subprocess.check_output(
        ["gh", "api", "-X", "GET", "search/issues", "-f", f"q={q}", "-F", "per_page=1"],
        text=True,
    )
    return int(json.loads(out).get("total_count", 0))


def pypistats(path: str) -> dict:
    """GET against the pypistats.org JSON API (no auth needed).

    Sets a descriptive User-Agent so the request is identifiable and less
    likely to hit shared-IP rate limits on github-actions runners.
    """
    url = f"https://pypistats.org/api/packages/{PKG}{path}"
    req = urllib.request.Request(
        url,
        headers={"User-Agent": f"{REPO}-metrics-workflow (+https://github.com/{REPO})"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def fmt(n: int | float) -> str:
    """Format a number with thousands separators."""
    return f"{int(n):,}"


def safe_get(fn, default, *, on_error: list[str] | None = None):
    """Best-effort wrapper — never let a transient API hiccup blank METRICS.md.

    If ``on_error`` is provided, append the stringified error so the caller
    can distinguish "API failed" from "API returned empty data".
    """
    try:
        return fn()
    except (
        urllib.error.HTTPError,
        urllib.error.URLError,
        subprocess.CalledProcessError,
        KeyError,
        ValueError,
    ) as err:
        msg = str(err)
        print(f"warn: {msg}", file=sys.stderr)
        if on_error is not None:
            on_error.append(msg)
        return default


def main() -> int:
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d %H:%M UTC")

    repo = safe_get(lambda: gh(""), {})

    # Traffic endpoints require Administration: read — collect errors so we
    # can show a clear note in METRICS.md if the token is under-scoped.
    traffic_errors: list[str] = []
    clones = safe_get(
        lambda: gh("/traffic/clones"),
        {"count": 0, "uniques": 0, "clones": []},
        on_error=traffic_errors,
    )
    views = safe_get(
        lambda: gh("/traffic/views"),
        {"count": 0, "uniques": 0, "views": []},
        on_error=traffic_errors,
    )
    referrers = safe_get(lambda: gh("/traffic/popular/referrers"), [], on_error=traffic_errors)
    paths = safe_get(lambda: gh("/traffic/popular/paths"), [], on_error=traffic_errors)
    traffic_blocked = bool(traffic_errors)

    open_issues = safe_get(
        lambda: gh_search_count(f"repo:{REPO} is:open is:issue"), 0
    )
    open_prs = safe_get(
        lambda: gh_search_count(f"repo:{REPO} is:open is:pr"), 0
    )

    pypi_errors: list[str] = []
    recent = safe_get(lambda: pypistats("/recent")["data"], {}, on_error=pypi_errors)
    pypi_blocked = bool(pypi_errors)

    stars = repo.get("stargazers_count", 0)
    forks = repo.get("forks_count", 0)
    watchers = repo.get("subscribers_count", 0)

    last_day = recent.get("last_day", 0)
    last_week = recent.get("last_week", 0)
    last_month = recent.get("last_month", 0)

    lines: list[str] = []
    push = lines.append
    push(f"# {PKG} metrics")
    push("")
    push(f"_Last updated: {timestamp}. Auto-generated by `.github/workflows/metrics.yml`; do not edit by hand._")
    push("")
    push("## Snapshot")
    push("")
    if pypi_blocked:
        push(
            "> **PyPI download counts unavailable this run.** pypistats.org "
            "returned an error (often a transient rate-limit on shared CI "
            "IPs). Showing the last successful values would be misleading; "
            "the next run should recover automatically."
        )
        push("")
    push("| Metric | Value |")
    push("|---|---|")
    push(f"| PyPI downloads (last 24h) | {fmt(last_day)} |")
    push(f"| PyPI downloads (last 7d) | {fmt(last_week)} |")
    push(f"| PyPI downloads (last 30d) | {fmt(last_month)} |")
    push(f"| GitHub stars | {fmt(stars)} |")
    push(f"| GitHub forks | {fmt(forks)} |")
    push(f"| GitHub watchers | {fmt(watchers)} |")
    push(f"| Open issues | {fmt(open_issues)} |")
    push(f"| Open PRs | {fmt(open_prs)} |")
    push(f"| Repo clones (last 14d) | {fmt(clones.get('count', 0))} |")
    push(f"| Unique cloners (last 14d) | {fmt(clones.get('uniques', 0))} |")
    push(f"| Repo views (last 14d) | {fmt(views.get('count', 0))} |")
    push(f"| Unique visitors (last 14d) | {fmt(views.get('uniques', 0))} |")
    push("")
    push("## Plugin install proxy: daily clones (last 14d)")
    push("")
    push(
        f"`/plugin marketplace add {REPO}` is a git clone "
        "under the hood, so daily clone counts approximate plugin installs."
    )
    push("")
    if traffic_blocked:
        push(
            "> **Traffic data unavailable.** The workflow's token is missing "
            "`Administration: read` permission. Create a fine-grained PAT "
            "scoped to this repo with `Administration: read` + `Metadata: "
            "read`, save as repo secret `METRICS_TOKEN`, and re-run the "
            "workflow. See the comment header in "
            "[`.github/workflows/metrics.yml`](.github/workflows/metrics.yml) "
            "for full setup."
        )
        push("")
    daily = clones.get("clones", [])
    if daily:
        push("| Date | Clones | Unique cloners |")
        push("|---|---|---|")
        # GitHub returns oldest-first; show newest-first for readability.
        for row in reversed(daily):
            ts = row.get("timestamp", "")[:10]
            push(f"| {ts} | {fmt(row.get('count', 0))} | {fmt(row.get('uniques', 0))} |")
    else:
        push("_No clones recorded in the last 14 days._")
    push("")
    push("## Top referrers (last 14d)")
    push("")
    if referrers:
        push("| Source | Views | Unique |")
        push("|---|---|---|")
        for ref in referrers[:10]:
            push(
                f"| {ref.get('referrer', '?')} | {fmt(ref.get('count', 0))} "
                f"| {fmt(ref.get('uniques', 0))} |"
            )
    else:
        push("_No referrers recorded in the last 14 days._")
    push("")
    push("## Top paths (last 14d)")
    push("")
    if paths:
        push("| Path | Views | Unique |")
        push("|---|---|---|")
        for p in paths[:10]:
            label = p.get("path", "?")
            # Paths are full URLs; trim the repo prefix for readability.
            label = label.replace(f"/{REPO}", "") or "/"
            push(
                f"| `{label}` | {fmt(p.get('count', 0))} "
                f"| {fmt(p.get('uniques', 0))} |"
            )
    else:
        push("_No path traffic recorded in the last 14 days._")
    push("")
    push("## Drill deeper")
    push("")
    push(f"- [PyPI page](https://pypi.org/project/{PKG}/)")
    push(f"- [pepy.tech graphs](https://pepy.tech/project/{PKG})")
    push(f"- [pypistats daily history](https://pypistats.org/packages/{PKG})")
    push(f"- [GitHub Insights → Traffic](https://github.com/{REPO}/graphs/traffic)")
    push(f"- [Star history](https://star-history.com/#{REPO}&Date)")
    push("")

    OUTPUT.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
